# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_1(self):
        self.driver.get("https://qa2-pmteam.xyz/uk")
        self.driver.set_window_size(1920, 1040)
        self.driver.find_element(By.CSS_SELECTOR, ".userinfo__signIn > .button__content").click()
        self.driver.find_element(By.NAME, "login").click()
        self.driver.find_element(By.NAME, "login").send_keys("chistyakov")
        self.driver.find_element(By.NAME, "password").send_keys("Fyukbz8087702")
        self.driver.find_element(By.CSS_SELECTOR, ".input__icon_eye").click()
        self.driver.find_element(By.CSS_SELECTOR, ".button_size_m").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__menuBtn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".header__menuLogoutTxt").click()
